AMAZON_SQS_ENDPOINT=https://sqs.us-east-1.amazonaws.com/988650320779/standard
AMAZON_SQS_ACCESS_KEY=AKIAIQTE6XJARDRLQJDQ
AMAZON_SQS_SECRET_KEY=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
AMAZON_SQS_EXT_S3_ACCESS_KEY=AKIAIQTE6XJARDRLQJDQ
AMAZON_SQS_EXT_S3_SECRET_KEY=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
AMAZON_SQS_EXT_S3_BUCKET_NAME=standard-large-payloads